apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-e1820739-4515-4493-8e70-8dbeb0ba6814
  name: devfile-sample
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample
status:
  loadBalancer: {}
