apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-e1820739-4515-4493-8e70-8dbeb0ba6814
  name: devfile-sampleuzf7
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample
    weight: null
status: {}
